services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    x-develop:
      watch:
        - action: rebuild
          path: ./index.js
          target: .
    image: app:v1
    ports:
      - "3000:3000"